const cakeItems = [
    {
        id: 1,
        name: "Butterscotch cake with rasmalai 1Kg",
        category: "anniversary",
        rating: 5.0,
        Price: 1199,
        img: "images/anniversary/butterscotch-cake-with-rasmalai-1kg.jpg",
    },
    {
        id: 2,
        name: "Chocolate cream cake half kg",
        category: "anniversary",
        rating: 4.7,
        Price: 549,
        img: "images/anniversary/chocolate-cream-cake-half-kg.jpg",
    },
    {
        id: 3,
        name: "Chocolate truffle heart cake half kg",
        category: "anniversary",
        rating: 4.2,
        Price: 549,
        img: "images/anniversary/chocolate-truffle-heart-cake-half-kg.jpg",
    },
    {
        id: 4,
        name: "Heavenly Butterscotch cream cake half kg",
        category: "anniversary",
        rating: 4.9,
        Price: 549,
        img: "images/anniversary/heavenly-butterscotch-cream-cake-half-kg.jpg",
    },
    {
        id: 5,
        name: "Pearly Rosettes designer cake",
        category: "anniversary",
        rating: 4.8,
        Price: 1849,
        img: "images/anniversary/pearly-rosettes-designer-cake.jpg",
    },
    {
        id: 6,
        name: "Personalised photo special cake",
        category: "anniversary",
        rating: 4.7,
        Price: 949,
        img: "images/anniversary/personalised-photo-special-cake.jpg",
    },
    {
        id: 7,
        name: "Pretty propose pineapple cake half kg",
        category: "anniversary",
        rating: 5.0,
        Price: 599,
        img: "images/anniversary/pretty-propose-pineapple-cake-half-kg.jpg",
    },
    {
        id: 8,
        name: "Pretty Roses Black forest cake half kg",
        category: "anniversary",
        rating: 5.0,
        Price: 599,
        img: "images/anniversary/pretty-roses-black-forest-cake-half-kg.jpg",
    },
    {
        id: 9,
        name: "Rosy white forest cake half kg",
        category: "anniversary",
        rating: 5.0,
        Price: 649,
        img: "images/anniversary/rosy-white-forest-cake-half-kg.jpg",
    },
    {
        id: 10,
        name: "Butterscotch cake half kg",
        category: "birthday",
        rating: 4.5,
        Price: 499,
        img: "images/birthday/butterscotch-cake-half-kg.jpg",
    },
    {
        id: 11,
        name: "Bursting with delight cake half kg",
        category: "birthday",
        rating: 4.8,
        Price: 1399,
        img: "images/birthday/bursting-with-delight-cake.jpg",
    },
    {
        id: 12,
        name: "Chocolate walnut truffle cake half kg",
        category: "birthday",
        rating: 4.5,
        Price: 699,
        img: "images/birthday/chocolate-walnut-truffle-half-kg.jpg",
    },
    {
        id: 13,
        name: "Chocolaty truffle cake half kg",
        category: "birthday",
        rating: 4.7,
        Price: 549,
        img: "images/birthday/chocolaty-truffle-cake-half-kg.jpg",
    },
    {
        id: 14,
        name: "Fruit overload cake half kg",
        category: "birthday",
        rating: 5.0,
        Price: 699,
        img: "images/birthday/fruit-overload-cake-half-kg.jpg",
    },
    {
        id: 15,
        name: "Pineapple cake half kg",
        category: "birthday",
        rating: 4.9,
        Price: 549,
        img: "images/birthday/pineapple-cake-half-kg.jpg",
    },
    {
        id: 16,
        name: "Red velvet fresh cream cake half kg",
        category: "birthday",
        rating: 4.7,
        Price: 799,
        img: "images/birthday/red-velvet-fresh-cream-cake-half-kg.jpg",
    },
    {
        id: 17,
        name: "Tempting mango cake half kg",
        category: "birthday",
        rating: 5.0,
        Price: 699,
        img: "images/birthday/tempting-mango-cake-half-kg.jpg",
    },
    {
        id: 18,
        name: "Affection photo chocolate cake half kg",
        category: "wedding",
        rating: 5.0,
        Price: 1049,
        img: "images/wedding/affection-photo-chocolate-cake-half-kg.jpg",
    },
    {
        id: 19,
        name: "Pastel pearl chocolate cream cake 2kg",
        category: "wedding",
        rating: 5.0,
        Price: 1949,
        img: "images/wedding/pastel-pearl-chocolate-cream-cake-2-kg.jpg",
    },
    {
        id: 20,
        name: "Red velvet cake half kg",
        category: "wedding",
        rating: 4.5,
        Price: 799,
        img: "images/wedding/red-velvet-heart-cake-half-kg.jpg",
    },
    {
        id: 21,
        name: "Rose fondant cake chocolate 4kg",
        category: "wedding",
        rating: 5.0,
        Price: 7199,
        img: "images/wedding/rose-fondant-cake-chocolate-4kg.jpg",
    },
    {
        id: 21,
        name: "Rose heart chocolate cream cake half kg",
        category: "wedding",
        rating: 4.8,
        Price: 599,
        img: "images/wedding/rose-heart-chocolate-cream-cake-half-kg.jpg",
    },
    {
        id: 22,
        name: "Roses on top chocolicious cake half kg",
        category: "wedding",
        rating: 4.9,
        Price: 649,
        img: "images/wedding/roses-on-top-chocolicious-cake-half-kg.jpg",
    },
    {
        id: 23,
        name: "Special hearts truffle fondant cake 1kg",
        category: "wedding",
        rating: 5.0,
        Price: 1799,
        img: "images/wedding/special-hearts-truffle-fondant-cake-1-kg.jpg",
    },
    {
        id: 24,
        name: "White chocolate fantasy wedding cake 2kg",
        category: "wedding",
        rating: 5.0,
        Price: 1949,
        img: "images/wedding/white-chocolate-fantasy-wedding-cake-2-kg.jpg",
    }
];

export {cakeItems};